[package]
name = "sex_offender_search"
version = "0.1.0"
authors = ["d-rezzer"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
bytes = "0.4"

[dependencies.rusqlite]
version = "0.18.0"
features = ["bundled"]