
= Introduction to the Sex Offender Service: How to search
Ryan Lee Martin <ryanlmartin@gmail.com>
:icons: font
:source-highlighter: hightlightjs 
:highlightjs-theme: xcode
v1.0, 2019-06-14
:toc: left
== First Section

=== That's just like, your opinion man
[quote, Walter, Big Lebowski]
____
The dude abides
____


.Table Neato
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3 

|This is neat, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===



++++
<p>
Content in a passthrough block is passed to the output unprocessed.
That means you can include raw HTML, like this embedded Gist:
</p>

<script src="https://gist.github.com/mojavelinux/5333524.js">
</script>
++++

****
The so called sidebar
****


.Toggle me
[%collapsible]
====
Watch this: 
Now is the winter of our discontent
====

== Second Section 

.Tip List
****
* item 1 

TIP: Man with itchy but wake up with smelly finger

[TIP]
====

An admonition block may contain complex content.

.A list
- one
- two
- three

Another paragraph.

====
* Item 2 Very nice very nice
****

.AsciiDoc history
****
AsciiDoc was first released in Nov 2002 by Stuart Rackham.
It was designed from the start to be a shorthand syntax
for producing professional documents like DocBook and LaTeX.
****

//.Rust is cool
/nt=4]
//----
//nclude::src/main.rs[lines=16..32]
//----


[source, rust]
----
let x = 5;
let mut p = &x;
----

[source, bash]
----
$ sudo apt install piggy
$ sudo apt update
$ sudo apt upgrade
----
